[package]
name = "logger"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
anyhow.workspace = true
chrono = "0.4.35"
env_logger = "0.11.6"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.10.1" 