[package]
name = "settings_manager"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_yaml = "0.9.33"
once_cell = "1.19.0"

[dev-dependencies]
tempfile = "3.10.1"
assert_cmd = "2.0" 